# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - onni-bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_d9b6a7920d5c4f54a28e744014fa3fe3 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ce8f39dd6a604c878b491a5f2e49323d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d9b6a7920d5c4f54a28e744014fa3fe3 }}/deaptic/onni-bot:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'onni-bot'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7df27df7537043c298301452e2d327a6 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d9b6a7920d5c4f54a28e744014fa3fe3 }}/deaptic/onni-bot:${{ github.sha }}'