name: Build and deploy container app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/onni-bot:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"

    steps:
      - name: Deploy to Vultr VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VULTR_HOST }}
          username: ${{ secrets.VULTR_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}
            export OPENAI_API_TOKEN=${{ secrets.OPENAI_API_TOKEN }}
            export OPENAI_CUSTOM_MODEL_ID=${{ secrets.OPENAI_CUSTOM_MODEL_ID }}
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            docker stop onni-bot || true
            docker rm onni-bot || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/onni-bot:latest
            docker run -d -p 80:80 --name onni-bot ${{ secrets.DOCKERHUB_USERNAME }}/onni-bot:latest
            docker logout
